; ============================================================
; AI网络安全智能分析系统 - Inno Setup 安装脚本
; 功能：
;   1. 标准安装向导（中文/英文），无需管理员权限
;   2. 安装时可选填写大模型 API Key（写入 .env，不写死进程序）
;   3. 创建开始菜单/桌面快捷方式
;   4. 安装完成后可立即启动
; 编译：ISCC.exe installer.iss
; ============================================================

[Setup]
AppId={{8A2B9C31-4E7D-4F3A-9C21-5D6E7F8A9B0C}
AppName=AI网络安全智能分析系统
AppVersion=1.3.1
AppVerName=AI网络安全智能分析系统 1.3.1
AppPublisher=AI Network Security Analyzer
DefaultDirName={autopf}\AI网络安全分析系统
DefaultGroupName=AI网络安全智能分析系统
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=installer_output
OutputBaseFilename=AI网络安全智能分析系统_Setup_1.3.1
Compression=lzma2/ultra
SolidCompression=yes
WizardStyle=modern
SetupIconFile=assets\app_icon.ico
UninstallDisplayIcon={app}\AI网络安全分析系统.exe
VersionInfoVersion=1.3.1
VersionInfoDescription=AI网络安全智能分析系统 安装程序
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\AI网络安全分析系统\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; 注意：.env 不在打包产物中（API Key 绝不写死），由安装流程或首次运行引导生成

[Icons]
Name: "{group}\AI网络安全智能分析系统"; Filename: "{app}\AI网络安全分析系统.exe"; WorkingDir: "{app}"
Name: "{autodesktop}\AI网络安全智能分析系统"; Filename: "{app}\AI网络安全分析系统.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\AI网络安全分析系统.exe"; Description: "{cm:LaunchProgram,AI网络安全智能分析系统}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\.env"
Type: filesandordirs; Name: "{app}\data"

[Code]
var
  ApiKeyPage: TInputQueryWizardPage;

{ 安装向导：API 配置页（可选） }
procedure InitializeWizard;
begin
  ApiKeyPage := CreateInputQueryPage(wpSelectTasks,
    '大模型 API 配置（可选）',
    '填写你的大模型 API Key，用于 AI 威胁研判与安全问答',
    '该配置将保存到安装目录下的 .env 文件，不会写入程序本体，可随时修改。' + #13#10 +
    '留空可跳过，首次启动程序时会再次弹出配置引导。' + #13#10 + #13#10 +
    '常用服务商：' + #13#10 +
    '  智谱AI（免费）  https://open.bigmodel.cn/api/paas/v4   glm-4-flash' + #13#10 +
    '  DeepSeek        https://api.deepseek.com              deepseek-chat' + #13#10 +
    '  通义千问        https://dashscope.aliyuncs.com/compatible-mode/v1   qwen-turbo' + #13#10 +
    '  Ollama 本地模型 http://localhost:11434/v1             qwen2.5:7b（Key 填任意值）');

  ApiKeyPage.Add('API Key：', True);
  ApiKeyPage.Add('API 地址 (Base URL)：', False);
  ApiKeyPage.Add('模型名称：', False);

  ApiKeyPage.Values[0] := '';
  ApiKeyPage.Values[1] := 'https://open.bigmodel.cn/api/paas/v4';
  ApiKeyPage.Values[2] := 'glm-4-flash';
end;

{ 安装完成后写入 .env }
procedure CurStepChanged(CurStep: TSetupStep);
var
  EnvPath, Content, Key, BaseUrl, Model: String;
begin
  if CurStep = ssPostInstall then
  begin
    Key := Trim(ApiKeyPage.Values[0]);
    BaseUrl := Trim(ApiKeyPage.Values[1]);
    Model := Trim(ApiKeyPage.Values[2]);

    if BaseUrl = '' then
      BaseUrl := 'https://open.bigmodel.cn/api/paas/v4';
    if Model = '' then
      Model := 'glm-4-flash';

    EnvPath := ExpandConstant('{app}\.env');

    if Key <> '' then
    begin
      { User provided key: write full config (pure ASCII to avoid encoding issues) }
      Content := '# Generated by installer' + #13#10 +
                 'LLM_API_KEY=' + Key + #13#10 +
                 'LLM_BASE_URL=' + BaseUrl + #13#10 +
                 'LLM_MODEL=' + Model + #13#10;
    end
    else
    begin
      { User skipped: write template; first launch of the app will prompt for config }
      Content := '# API key not configured yet; first launch will prompt' + #13#10 +
                 'LLM_API_KEY=' + #13#10 +
                 'LLM_BASE_URL=' + BaseUrl + #13#10 +
                 'LLM_MODEL=' + Model + #13#10;
    end;

    SaveStringToFile(EnvPath, Content, False);
  end;
end;
